spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:memtestdb
    username: sa

  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: ".jsp"
  h2:
    console:
      enabled: true

server:
  servlet:
    jsp:
      init-parameters:
        development: true
